#!/bin/bash
set -o pipefail

# shellcheck disable=SC1091
. common.sh

# check all the .json files except those under ./vendor
STATUS=0
for filename in "${JSON_FILES[@]}"; do
    jqout=$("$JQ" . --sort-keys "$filename" 2>&1)
    if [ $? -ne 0 ]; then
        while read -r line; do
	        echo "[jq]: $filename - $line"
        done < <(echo  "$jqout" | egrep -v '^$')
        STATUS=1
    elif ! (echo "$jqout" | diff "$filename" - > /dev/null) ; then
        echo "[jq]: $filename isn't formatted correctly"
        STATUS=1
    fi
done

exit "$STATUS"
